#pragma once

enum class TokenType
{
	// one-char
	LPAREN, RPAREN, LBRACE, RBRACE, COLON,
	COMMA, DOT, PLUS, MINUS, ASTK, SLASH, SEMICOLON,
	QUESTION,

	// one/two-char
	BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
	PLUS_EQUAL, MINUS_EQUAL, ASTK_EQUAL,
	SLASH_EQUAL, PLUS_PLUS, MINUS_MINUS,

	// Literals
	IDENTIFIER, STRING, NUMBER,

	// Keywords
	AND, CLASS, ELSE, ELIF, FALSE, FN, FOR, IF, NIL, OR,
	PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE, INPUT,

	END
};